### PR TITLE
Add lines to json LOC

### PR DESCRIPTION
**Pull request by AndreasHeiberg**
Currently LOC outputted from graphql_ast_to_json() only contains columns. The PHP extension for libgraphqlparser is using graphql_ast_to_json() to reduce the amount of c code required to integrate with PHP. The outcome being that I have no way of getting to the line information. I suppose I could write a better PHP extension, but wondering if you guys would be amenable to simply add the information to the json blob?

### CODE REVIEW

**Comment by swolchok** [comment]
I thought I had a good reason for making this work the way it does (matching the graphql-js format), but it looks like the information it prints now is close to useless. Happy to take a patch that fixes it, but:

1) Please fix the CI build (there are tests that make sure the JSON output doesn't change), and
2) Could you make it `{"start": {"line": 123, "column": 456}, "end": {...}}`? I appreciate the attempt at backward compatibility, but we're an 0.x release and therefore can inconvenience consumers. (Also, consumers that try to use our location information are getting nonsense anyway.)

**Comment by AndreasHeiberg** [comment]
1. Will do
2. Cool, much more sensical just didn't wanna valse in and make something backwards incompatible.

**Comment by AndreasHeiberg** [comment]
QQ how do I run these tests locally?

**Comment by swolchok** [comment]
> nonsense

they're getting column number information without line number information, which isn't useful. I had thought we were giving them a character offset, which would be useful but not ideal.

> how to run tests

see https://github.com/graphql/libgraphqlparser/blob/master/.travis.yml

**Comment by AndreasHeiberg** [comment]
:man_facepalming: didn't think to look in the travis setup.

But yeah fixed the tests.

**Pull request merged**
