### PR TITLE
Generate ruby bindings

### PR DESCRIPTION
**Pull request by eapache**
@swolchok @dylanahsmith

This is the first implementation of a generator for ruby bindings. I have a local copy of a gem structure that builds the resulting code and runs a bunch of ruby-land tests against it; everything looks promising so far. I expect at some point we'll open up the gem itself as well.

It's been a while since I've done any serious python, so I expect I've done some weird things that will have to be fixed. Looking forward to sharpening that skillset again :)

### CODE REVIEW

**Comment by swolchok** [comment]
I think from an organizational perspective it would make sense to keep non-trivial language bindings for libgraphqlparser in separate repos for several reasons. Perhaps you could create libgraphqlparser-ruby?

1) AFAIK, packaging and shipping separately is standard practice for C libraries + scripting language bindings in general; at most, you get the author's favorite languages in the main repo. (Python was just handy for an example; I would similarly encourage libgraphqlparser-python with idiomatic Python bindings, like [PyClang](https://github.com/wolfhechel/pyclang).
2) The bindings in the repo right now are intended as toy examples to show what can be done and have several warts (like making you call free explicitly in scripting language code), whereas I imagine these are intended for production use.

What do you think?

**Comment by eapache** [comment]
I tend to agree, it's just a bit awkward because `ast.py` hardcodes the languages it knows about and their lookup paths, so to store this in a separate repo I'd have to do all sorts of weird `cp`ing around of files to get it to run.

Would you take a PR making the arguments to `ast.py` more flexible at the cost of being a bit more verbose?

**Comment by swolchok** [comment]
> Would you take a PR making the arguments to ast.py more flexible at the cost of being a bit more verbose?

Absolutely! Definitely needs to be easier to use from other repos.

**Comment by rmosolgo** [comment]
:joy: go get 'em @eapache !!

**Pull request closed without merging**
