### PR TITLE
[conan] Add conan file

### PR DESCRIPTION
**Pull request by Fohlen**
Hey there! I really like this library but feel it is missing a [conan](https://conan.io/) receipt. So here it is. Please also consider uploading the package to the [conan centre](https://bintray.com/conan/conan-center) so that it can be used by others!

### CODE REVIEW

**Comment by swolchok** [comment]
I think there's a lot of established precedent for package managers maintaining packages in their own repo rather than pushing the packages upstream. For example, both Debian (apt) and Homebrew work that way. Why is Conan different?

**Comment by Fohlen** [comment]
@swolchok as far as I know there isn't a clear consensus among the conan community.
There are overall maintainer collectives, such as @bincrafters. They might eventually package and maintain something if it has enough demand. Nevertheless I'd say that this isn't really an argument either: there are loads of other languages that use the model of self maintenance (essentially anything not C/C++ that I am aware of: look at NPM, PIP, Maven, you name it).

I could take on here and maintain this package on my own but it is probably in your best interest of having control over the repo because the graphql organization is essentially maintaining it.

**Comment by swolchok** [comment]
> there are loads of other languages that use the model of self maintenance (essentially anything not C/C++ that I am aware of: look at NPM, PIP, Maven, you name it

Hmm, that's a good point. I would argue that those package managers are the clear winner for their language and are developer-oriented. In contrast, I've never heard of conan before; from my perspective, it seems to be a new entrant in a crowded field. Am I just out of date?

**Comment by Fohlen** [comment]
@swolchok well, conan is not that new, but not that old either. It's essentially the missing package manager for C/C++ that recognised that it's not absolutely necessary to be written in C/C++ itself (that is why most other package managers, including CMake failed imho). Story goes that conan was previously called biicode but the company behind it went bankrupt. Now it's baked by JFrog and if you have a look at the [conan centre](https://bintray.com/conan/conan-center) there are *loads* of packages already. I guess this is more of a private discussion now and we shouldn't dive more off-topic here!

**Comment by swolchok** [comment]
It [looks like](https://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html) maintaining packages downstream is a supported Conan workflow. I think it would be best if the package was maintained that way.

**Pull request closed without merging**
