### PR TITLE
Python bindings using cython

### PR DESCRIPTION
**Pull request by mpaolini**
This binding offers a class-based binding and works on python3

### CODE REVIEW

**Comment by swolchok** [comment]
Love it! This should definitely be faster than ctypes/libffi. Could I trouble you to put this up as a separate repo instead? I think it makes more organizational sense to keep non-toy/example language bindings in separate repos -- [here's my reasoning in more detail.](https://github.com/graphql/libgraphqlparser/pull/12#issuecomment-140867376)

#13 from yesterday should make it easier to integrate with ast.py from a separate project.

Let me know if you've got any thoughts on the matter!

**Comment by mpaolini** [comment]
OK for the separate repo, only need `ast.py` from graphql/libgraphqlparser. You create it or I do?

**Comment by swolchok** [comment]
> You create it or I do?

Please feel free!

**Comment by mpaolini** [comment]
OK the new repo is https://github.com/elastic-coders/py-graphqlparser
closing this one

**Pull request closed without merging**
