### PR TITLE
Change install include files

### PR DESCRIPTION
**Pull request by kurayama**
Install only C/C++ headers.
Also fixes missing headers (location.hh, etc.) when including in own files.

### CODE REVIEW

**Comment by kurayama** [comment]
I tested again and seems to work without flags, did you use any? 
Can you test again? It was probably the CMAKE_CURRENT_BINARY_DIR variable messing up

**Comment by swolchok** [comment]
OK, now the C directory is getting created, but the generated headers (e.g., `c/GraphQLAst.h`) aren't included:

```
$ find
.
./include
./include/graphqlparser
./include/graphqlparser/AstNode.h
./include/graphqlparser/c
./include/graphqlparser/c/GraphQLAstNode.h
./include/graphqlparser/c/GraphQLAstVisitor.h
./include/graphqlparser/c/GraphQLParser.h
./include/graphqlparser/GraphQLParser.h
./include/graphqlparser/JsonVisitor.h
./include/graphqlparser/lexer.h
./include/graphqlparser/location.hh
./include/graphqlparser/position.hh
./include/graphqlparser/stack.hh
./include/graphqlparser/syntaxdefs.h
./lib
./lib/libgraphqlparser.dylib
```

I tested using an out-of-tree build: `mkdir build && cd build && cmake .. -Dtest=1 -DCMAKE_INSTALL_PREFIX:PATH=/Users/swolchok/libgraphqlparser/install && cmake --build .`

**Comment by swolchok** [comment]
I think the problem is that the GLOB method can't really support out-of-tree builds. I'll send out a change to at least include the .hh files.

**Comment by swolchok** [comment]
I just pushed https://github.com/graphql/libgraphqlparser/commit/3675c74bf6f4249bf6d32708073c0f401b92c32e to install the missing headers. Feel free to rebase and get this working with out-of-source builds!

**Comment by swolchok** [comment]
closing because this has gone stale; feel free to open another PR

**Pull request closed without merging**
